import sys

WHITE = '#FFFFFF'
BLACK = '#000000'

L_GRAY = '#d9d9d9'
D_GRAY = '#a3a3a3'

GREEN = '#06e537'
FUSCHIA = '#E91E63'
LIME = '#A0FF1B'
CYAN = '#1DFFDD'
D_BLUE = '#122a3d'
PURPLE = '#B422FF'
SALMON = '#FF8684'
SALMON_LIGHT = '#FFAF8C'
PALE_YELLOW = '#FFEDA9'

D_GREEN = '#05CE00'

YES = '#48FF23' #7EFF2C'
NO = '#E91E3A'


# GENERAL COLORS
ACTIVE_COLOR = LIME # Change this to change all highlight colors
ACTIVE_COLOR_LIGHT = PALE_YELLOW # Change this to change all highlight colors

BG_MAIN_NUMBER = D_BLUE
FG_MAIN_NUMBER = WHITE

BG_MAIN_TITLE = ACTIVE_COLOR
FG_MAIN_TITLE = D_BLUE

BG_TITLE = WHITE # ACTIVE_COLOR
FG_TITLE = D_BLUE

TOP_BG_COLOR = D_BLUE
FG_COLOR = D_BLUE


BG_DISABLED_COLOR = L_GRAY
FG_DISABLED_COLOR = D_GRAY

TAB_BG_COLOR = WHITE
TAB_HL_COLOR = LIME



# DATA TAB


DATASET_BG = WHITE

TYPE_BG = WHITE
FILTER_BG = WHITE
PROCESS_BG = WHITE


DATASET_LBL_BG = L_GRAY
DATASET_LBL_FG = FG_COLOR

DATASET_STR_BG = WHITE
DATASET_STR_FG = FG_COLOR

DATASET_ENTRY_BG = WHITE
DATASET_ENTRY_FG = FG_COLOR

DATASET_BTN_BG = ACTIVE_COLOR
DATASET_BTN_FG = FG_COLOR
DATASET_BTN_BG_ACTIVE = LIME
DATASET_BTN_FG_ACTIVE = FG_COLOR


VARDESC_BG = DATASET_BG

VARDESC_LBL_BG = DATASET_LBL_BG
VARDESC_LBL_FG = DATASET_LBL_FG

VARDESC_STR_BG = DATASET_STR_BG
VARDESC_STR_FG = DATASET_STR_FG

VARDESC_ENTRY_BG = DATASET_ENTRY_BG
VARDESC_ENTRY_FG = DATASET_ENTRY_FG

VARDESC_BTN_BG = L_GRAY
VARDESC_BTN_FG = DATASET_BTN_FG
VARDESC_BTN_BG_ACTIVE = VARDESC_BTN_BG # TODO change when functional
VARDESC_BTN_FG_ACTIVE = DATASET_BTN_FG_ACTIVE

START_BTN_BG = DATASET_BTN_BG
START_BTN_FG = DATASET_BTN_FG
START_BTN_BG_ACTIVE = DATASET_BTN_BG_ACTIVE
START_BTN_FG_ACTIVE = DATASET_BTN_FG_ACTIVE



# TEST TAB

SELECT_BG = WHITE
SELECT_BG_HL = ACTIVE_COLOR_LIGHT

SELECT_LBL_BG = L_GRAY
SELECT_LBL_FG = FG_COLOR

SELECT_STR_BG = WHITE
SELECT_STR_FG = FG_COLOR

SELECT_ENTRY_BG = WHITE
SELECT_ENTRY_FG = FG_COLOR
SELECT_ENTRY_BG_INS = D_BLUE

SELECT_BTN_BG = ACTIVE_COLOR
SELECT_BTN_FG = FG_COLOR
SELECT_BTN_BG_ACTIVE = ACTIVE_COLOR
SELECT_BTN_FG_ACTIVE = FG_COLOR




# ABOUT TAB

ABOUT_BG = WHITE

ABOUT_LBL_BG = L_GRAY
ABOUT_LBL_FG = FG_COLOR

ABOUT_STR_BG = WHITE
ABOUT_STR_FG = FG_COLOR

