





# DATA tab entries


TITLE_DATASET = '''Dataset'''

LBL_DATASET_VARDESC = '''Variable Description:'''
BTN_DATASET_UPLOAD = '''Upload'''
LBL_DATASET_POPULATION = '''Population Dataset:'''

BTN_START = '''Start'''
TITLE_VARDESC = '''Variable Description Generator (Not yet functional)'''


LBL_VARDESC_VARFILE = '''Variable File:'''
BTN_VARDESC_UPLOAD = '''Choose File...'''

LBL_VARDESC_VALFILE = '''Values File:'''

# ABOUT tab entries
TITLE_ABOUT = '''About'''

LBL_ABOUT_VER = '''Version:'''
STR_ABOUT_VER = '''OOTO Miner v. 2.0.0'''

LBL_ABOUT_AUTHOR = '''Author:'''
STR_ABOUT_AUTHOR = '''TE3D House'''


LBL_ABOUT_AFFILIATION = '''Affiliation:'''
STR_ABOUT_AFFILIATION = '''De La Salle University - Laguna'''


# Constant values

# TABS Parent frame
TAB_REL_X = 0
TAB_REL_Y = 0
TAB_REL_W = 1
TAB_REL_H = 1

TAB_CHILD_PADDING_TOP = 0.02

# TABS Element
TAB_ELEMENT_REL_X = 0
TAB_ELEMENT_REL_W = 1

TAB_DATA_ELEMENT_REL_X = 0
TAB_DATA_ELEMENT_REL_W = 0.8

# TABS Child frames
TAB_CHILD_REL_X = 0.01
TAB_CHILD_REL_Y = 0.01
TAB_CHILD_REL_W = 0.98
TAB_CHILD_REL_H = 0.25 # (3 elements)

TAB_CHILD_REL_H_SMALL = 0.15 # (2 elements)


# TABS Child frames (DATASET)
TAB_DATASET_REL_X = 0.1
TAB_DATASET_REL_Y = 0.01
TAB_DATASET_REL_W = 0.80
TAB_DATASET_REL_H = TAB_CHILD_REL_H_SMALL # TAB_CHILD_REL_H


# TABS Child frames (VARDESC)
TAB_VARDESC_REL_X = TAB_DATASET_REL_X
TAB_VARDESC_REL_Y = TAB_DATASET_REL_Y
TAB_VARDESC_REL_W = TAB_DATASET_REL_W
TAB_VARDESC_REL_H = TAB_DATASET_REL_H

# TABS Child frames (ABOUT)
TAB_ABOUT_REL_X = 0.1
TAB_ABOUT_REL_Y = 0.01
TAB_ABOUT_REL_W = 0.80
TAB_ABOUT_REL_H = TAB_CHILD_REL_H


# TABS Child generic elements
TAB_CHILD_REL_H = 0.18 # 0.20 minus padding

# TABS Child elements (2 in a row: label | text)
TAB_CHILD_LBL_REL_X = 0.01
TAB_CHILD_LBL_REL_Y = 0.02
TAB_CHILD_LBL_REL_W = 0.18 # 0.20
TAB_CHILD_LBL_REL_H = TAB_CHILD_REL_H

TAB_CHILD_STR_REL_W = 0.78 # 0.80



# TABS Child elements (3 in a row: label | entry | button)
TAB_3CHILD_LBL_REL_X = 0.01
TAB_3CHILD_LBL_REL_Y = 0.02
TAB_3CHILD_LBL_REL_W = 0.18 # 0.20 - (2 * TAB_3CHILD_LBL_REL_X
TAB_3CHILD_LBL_REL_H = TAB_CHILD_REL_H

TAB_3CHILD_LBL_REL_Y_SMALL = 0.05
TAB_3CHILD_LBL_REL_H_SMALL = 0.33

TAB_3CHILD_ENTRY_REL_W = 0.60

TAB_3CHILD_BTN_REL_W = 0.18 # 0.20 - (2 * TAB_3CHILD_LBL_REL_X)